# Generated by Django 5.1.6 on 2025-02-16 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cell_number', models.CharField(max_length=15, unique=True)),
                ('tower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map_app.tower')),
            ],
        ),
    ]
