"""
Django settings for mapui project.

Generated by 'django-admin startproject' using Django 5.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
import os
from pathlib import Path
from decouple import config, Csv  # Import config and Csv for allowed hosts

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# --- CORE SECURITY AND HOST SETTINGS ---

# SECURITY WARNING: keep the secret key used in production secret!
# Fetch from environment variable (required)
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
# Fetch from environment variable, defaults to True for safety if not set
DEBUG = config('DEBUG', default=True, cast=bool)

# Fetch ALLOWED_HOSTS from env, split by comma, and include specified host
# Use Csv to parse the comma-separated string from the .env file
allowed_hosts_string = config(
    'ALLOWED_HOSTS',
    default='127.0.0.1, localhost,ntc-intern.onrender.com'
)

ALLOWED_HOSTS = [h.strip() for h in allowed_hosts_string.split(',')]

# Ensure the specific host is included if not in the environment variable
if 'ntc-intern.onrender.com' not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append('ntc-intern.onrender.com')


# Application definition
INSTALLED_APPS = [
    # Custom apps
    'map_app',
    'rbac',
    'authentication.apps.AuthenticationConfig',

    # Django GIS
    # 'django.contrib.gis',

    # Default Django apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # 'django_extensions'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 'rbac.middleware.RBACMiddleware',
    # 'rbac.middleware.ActivityLogMiddleware',
]

ROOT_URLCONF = 'mapui.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                # Must write this to pass auth to another app
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.static',
            ],
        },
    },
]

WSGI_APPLICATION = 'mapui.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        # Use config instead of os.getenv for consistency with decouple
        'NAME': config('DB_NAME', default='mapdata'),
        'USER': config('DB_USER', default='postgres'),
        'PASSWORD': config('DB_PASSWORD', default='admin'),
        'HOST': config('DB_HOST', default='localhost'),
        'PORT': config('DB_PORT', default='5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators
AUTH_USER_MODEL = 'authentication.User'
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kathmandu'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    # Path to your app's static files
    os.path.join(BASE_DIR, 'map_app/static'),
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
LOGIN_URL = "/login/"  # URL to redirect unauthenticated users
LOGIN_REDIRECT_URL = "map_app:home"  # Redirect after successful login
LOGOUT_REDIRECT_URL = "authentication:login"  # Redirect after logout


RENDER_EXTERNAL_HOSTNAME = os.environ.get('RENDER_EXTERNAL_HOSTNAME')
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)

# Add your Render domain
if not DEBUG:
    ALLOWED_HOSTS.extend([
        '.onrender.com',
        '.ntc-intern.onrender.com'  # Replace with actual app name
    ])

# CSRF settings for your specific domain
CSRF_TRUSTED_ORIGINS = [
    'https://ntc-intern.onrender.com',
    'https://*.ntc-intern.onrender.com',
]

# Essential for iOS/Safari ITP compatibility
SESSION_COOKIE_SAMESITE = 'None'
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SAMESITE = 'None'
CSRF_COOKIE_SECURE = True

# Add Render external hostname to CSRF trusted origins
if RENDER_EXTERNAL_HOSTNAME:
    CSRF_TRUSTED_ORIGINS.append(f'https://{RENDER_EXTERNAL_HOSTNAME}')
