name: Docker Django CI

on:
  push:
    branches:
      - master
      - firebase
  pull_request:
    branches:
      - master
      - firebase

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python (only for linting, not for migrations)
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'
      
      # Step 3: Setting up Docker using compose file
      - name: Set up Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose
          docker --version
          docker-compose --version  

      - name: Build and Start Containers
        run: docker-compose up -d --build

      # Step 4: Create Firebase credentials file
      - name: Create Firebase credentials file
        run: |
          mkdir -p Firebase
          echo "${{ secrets.FIREBASE_CREDENTIALS_JSON }}" > Firebase/pathto_json.json

      - name: Wait for PostgreSQL
        run: |
          for i in {1..10}; do
            if docker exec django_app pg_isready -h db -U postgres; then
              echo "PostgreSQL is ready!"
              break
            fi
            echo "Waiting for PostgreSQL..."
            sleep 5
          done

      - name: Run Django Migrations
        run: docker exec django_app python manage.py migrate

      # Step 9: Test the Django application
      - name: Test Django application
        run: |
          curl -f http://localhost:8000 || exit 1  # Check if the app is running

      # Step 10: Stop and remove Docker container
      - name: Stop and remove Docker container
        run: |
          docker-compose down
